# Generated by Django 5.1.4 on 2025-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Profile pics',
        ),
        migrations.AddField(
            model_name='profile',
            name='Profile picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
