# Generated by Django 5.1.4 on 2025-01-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_profile_profile_pics_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Profile picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Profile picture'),
        ),
    ]
