# Generated by Django 5.1.4 on 2025-01-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Profile picture'),
        ),
    ]
